services:
    yuwway.form.registration:
        class: Yuwway\UserBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: yuwway_user_registration }
    fos_user.user_provider.email:
        class: Yuwway\UserBundle\Security\EmailUserProvider
        arguments:
            - '@fos_user.user_manager'
    image.uploader:
        class: Yuwway\UserBundle\Services\FileUploader
        arguments: ['%profile_image_directory%']

    yuwway.doctrine_listener:
        class: Yuwway\UserBundle\EventsListener\DoctrineListener
        arguments: ['@image.uploader','%profile_image_directory%']
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: postLoad }