services:
    yuwway.form.registration:
        class: Yuwway\UserBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: yuwway_user_registration }
    fos_user.user_provider.email:
        class: Yuwway\UserBundle\Security\EmailUserProvider
        arguments:
            - '@fos_user.user_manager'
