fos_comment_api:
    type: rest
    resource: "@FOSCommentBundle/Resources/config/routing.yml"
    prefix: /api
    defaults: { _format: html }

medlend_pugx:
    resource: "@MedlendPUGXBundle/Controller/"
    type:     annotation
    prefix:   /

yuwway_user:
    resource: "@YuwwayUserBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

genemu_base64:
    resource: "@GenemuFormBundle/Resources/config/routing/base64.xml"
